# Generated by Django 4.0.4 on 2022-05-27 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('pools', models.IntegerField(default=0)),
                ('percent', models.FloatField(default=0.0)),
                ('pool_date', models.DateField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meters.branches')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meters.meter')),
            ],
        ),
    ]
